"""Switch to UUIDs for primary keys and fix timestamp default

Revision ID: c072ff1cd1b4
Revises: 5fecdd1439d9
Create Date: 2025-06-06 15:01:01.849022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c072ff1cd1b4'
down_revision: Union[str, None] = '5fecdd1439d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing tables
    op.drop_table('document')
    op.drop_table('user')

    # Recreate tables with the new schema
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This is a destructive upgrade, so the downgrade is also destructive.
    op.drop_table('document')
    op.drop_table('user')

    # Recreate tables with the old schema
    op.create_table('user',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_table('document',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('upload_timestamp', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
        sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='document_user_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='document_pkey')
    )
    # ### end Alembic commands ###
